apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: cluster-stronghold
  name: cluster-stronghold-loadbalanced
  namespace: stronghold
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cluster-stronghold.home.ohnozombi.es
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: cluster-stronghold
    cnpg.io/instanceRole: primary
