apiVersion: batch/v1
kind: CronJob
metadata:
  name: audiobook-importer
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: audiobook-importer
spec:
  suspend: {{ .audiobookImporter.enabled | not }}
  schedule: "*/5 * * * *"
  timeZone: "America/Chicago"
  jobTemplate:
    metadata:
      labels:
        {{- include "stronghold.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: audiobook-importer
    spec:
      template:
        metadata:
          labels:
            {{- include "stronghold.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: audiobook-importer
        spec:
          serviceAccountName: audiobook-importer
          restartPolicy: Never
          containers:
            - name: stronghold
              image: "{{- include "stronghold.image" . }}"
              args:
                - ./stronghold
                - "-c"
                - "/etc/stronghold/config.yaml"
                - "audiobook-importer"
              imagePullPolicy: IfNotPresent
              resources: {}
              envFrom:
                {{- include "stronghold.envFrom" . | nindent 16 }}
              volumeMounts:
                {{- if .Values.volumeMounts }}
                  {{- toYaml .Values.volumeMounts | nindent 16 }}
                {{- end }}
                - name: config
                  mountPath: /etc/stronghold/
          volumes:
            {{- if .Values.volumes }}
              {{- toYaml .Values.volumes | nindent 12 }}
            {{- end }}
            - name: config
              configMap:
                name: stronghold-config

