apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "stronghold.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "stronghold.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: "{{- include "stronghold.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./stronghold
          args:
            - api
            - --config=/etc/stronghold/config.yaml
          envFrom:
            {{- include "stronghold.envFrom" . | nindent 16 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            - name: config
              mountPath: /etc/stronghold
              readOnly: true
      volumes:
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        - name: config
          configMap:
            name: stronghold-config


