apiVersion: v1
kind: ServiceAccount
metadata:
  name: audiobook-importer
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: audiobook-importer
  {{- with .Values.audiobookImporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.audiobookImporter.serviceAccount.automount }}


